### ISSUE TITLE
Levantar la aplicación de django

### ISSUE THREAD

**Issue by sirspock** [hrherrer/inf323-utfsm-grupo08#25]
<a href="https://github.com/sirspock"><img src="https://avatars0.githubusercontent.com/u/2365990?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sirspock](https://github.com/sirspock)**
_Wednesday Nov 22, 2017 at 12:51 GMT_
_Originally opened as https://github.com/sirspock/inf323/issues/30_

----

Utilizar Docker para levantar una aplicación simple con Django.

Tareas:
  - Levantar aplicación de Django + PostgresApp
  - Realizar un proxy en el nginx de la máquina para enviar solicitudes de django.grupoXX.mosorio.me al container (solamente http)
  - Debe realizar todo utilizando un docker-compose.yml, subir el docker compose al repositorio
  - Utilizar variables de entornos para colocar passwords y usuario a la base de datos

Documentación:
   - [Writing your first Django app, part 1](https://docs.djangoproject.com/en/1.11/intro/tutorial01/)
   - [Levantar aplicación de Django con Docker](https://www.caktusgroup.com/blog/2017/03/14/production-ready-dockerfile-your-python-django-app/)
  - [Select a storage driver | Docker Documentation](https://docs.docker.com/engine/userguide/storagedriver/selectadriver/)
   - ['Using Nginx as an application gateway with uWSGI and django'](https://www.nginx.com/resources/admin-guide/gateway-uwsgi-django/)

**Comment by mijara** [comment]
Otra cosa, no estoy muy seguro de cómo esperar a que Postgres levante antes de que Python intente hacer las migraciones, el depends_on no es suficiente ya que postgres tiene un startup time no despreciable.
