### ISSUE TITLE
Balanceo de carga

### ISSUE THREAD

**Issue by mosoriob** [hrherrer/inf323-utfsm-grupo08#29]
<a href="https://github.com/sirspock"><img src="https://avatars0.githubusercontent.com/u/2365990?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sirspock](https://github.com/sirspock)**
_Wednesday Dec 06, 2017 at 18:18 GMT_
_Originally opened as https://github.com/sirspock/inf323/issues/34_

----

### Descripción 

Dado que presenta dos containers en dos hosts distintos.
Realizar tareas de balanceo de carga con Nginx.
El servidor Nginx debe balancear la carga a los dos containers.

### Tareas

- Documente sobre los métodos de balanceo: Round‑Robin, Least Connections, Hash , IP Hash (HTTP only) 
- Configure la cantidad max_fails, slow_start y timeout para cada server
- Considere la persistencia de las sesiones para la elección del algoritmo.

### Documentación 

http://nginx.org/en/docs/http/load_balancing.html

**Comment by mijara** [comment]
Por defecto el balanceo es **Round-Robin** el cual va direccionando en orden a cada host.

**Least connected** intenta ser más justo cuando las conexiones son más largas, dirigiendo la petición al servidor que esté menos ocupado.

Los métodos anteriores no mantienen las sesiones de los usuarios ya que este puede llegar a parar a cualquiera de ellos.

**IP Hash**: La IP del cliente se usa como un hash para determinar a qué servidor va a parar el usuario, asegurando que siempre vaya al mismo, manteniendo la sesión persistente.

Se seleccionará esta última para considerar el punto 3 del issue.

**Comment by shelojara** [comment]
slow_start no puede ser usado con el método seleccionado para balanceo.
